import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fb",
        "surface-dim": "#d8dadd",
        "surface-bright": "#f8f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8eb",
        "surface-container-highest": "#e1e2e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#464651",
        "inverse-surface": "#2e3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#777682",
        "outline-variant": "#c7c5d2",
        "surface-tint": "#5257a3",
        primary: "#1d226e",
        "on-primary": "#ffffff",
        "primary-container": "#353a85",
        "on-primary-container": "#a3a8fb",
        "inverse-primary": "#bfc2ff",
        secondary: "#bb001e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e02933",
        "on-secondary-container": "#fffbff",
        tertiary: "#23265b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3a3d73",
        "on-tertiary-container": "#a7aae8",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bfc2ff",
        "on-primary-fixed": "#090c5e",
        "on-primary-fixed-variant": "#3a3f8a",
        "secondary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#ffb3ae",
        "on-secondary-fixed": "#410004",
        "on-secondary-fixed-variant": "#930015",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#bfc1ff",
        "on-tertiary-fixed": "#12144a",
        "on-tertiary-fixed-variant": "#3f4278",
        background: "#f8f9fc",
        "on-background": "#191c1e",
        "surface-variant": "#e1e2e5",
        "surface-lowest": "#ffffff",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm-mobile": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        touch: "48px",
      },
      maxWidth: {
        container: "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
